### ISSUE TITLE
JP Cost

### ISSUE THREAD

**Issue by TrueEftekas** [MarvinXLII/OctopathTravelerJobRandomizer#1]
Hello, I'd like to say thanks for making this fun little tool, I've really been enjoying it.
That being said, there's a small issue with JP cost adjustments when it comes to advanced jobs.
Advanced jobs normally cost 2k JP per skill except for the last one which costs 5K, but if you randomize JP costs they are reduced to being the same as the other classes. While I'm not opposed to the idea, I think it would be nicer as a separate option to reduce the JP costs of advanced jobs to standard ones rather than forcing it when randomized.

**Comment by MarvinXLII** [comment]
Thanks. JP cost reduction was intentionally added that way, though. As more of a casual player myself I agree it's a bit silly, but some speedrunners requested I do that for races to minimize JP grinding. I might make it something optional down the road, but with so many options at the moment I'm hesitant to add it and make the gui even more overwhelming.
